[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "softboiler_github_io_docs"
version = "0.0.0"
description = "Docs."
dependencies = [
    "linkify-it-py==2.0.3",
    "myst-nb==1.0.0",
    "nbformat==5.10.3",
    "sphinx==7.2.6",
    "sphinx-autobuild==2024.2.4",
    "sphinx-autodoc2==0.5.0",
    "sphinx-book-theme==1.1.2",
    "sphinx-design==0.5.0",
    "sphinx-thebe==0.3.1",
    "sphinx-tippy==0.4.1",
    "sphinx-togglebutton==0.3.2",
    "sphinxcontrib-bibtex==2.6.2",
    "sphinxcontrib-mermaid==0.9.2",
]

[tool.fawltydeps]
actions = ["check_undeclared"]
deps = ["docs/pyproject.toml", "pyproject.toml"]
code = ["docs/softboiler_github_io_docs"]
