# Simulate local dev run of `Sync-Py.ps1`
name: "contrib"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Sync-Py.ps1"
      - "scripts/softboiler_github_io_tools/**"
      - "scripts/pyproject.toml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/contrib.yml"
      - "scripts/Sync-Py.ps1"
      - "scripts/softboiler_github_io_tools/**"
      - "scripts/pyproject.toml"
defaults:
  run:
    shell: "pwsh"
jobs:
  contrib:
    strategy:
      matrix:
        runner:
          # - "macos-13"  # No code in `softboiler_github_io` right now
          # - "macos-14"  # No code in `softboiler_github_io` right now
          - "ubuntu-22.04"
          # - "windows-2022"  # No code in `softboiler_github_io` right now
    env:
      SYNC_PY_DISABLE_CI: true
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - run: "scripts/Sync-Py.ps1 -Compile -Lock -Version '3.11'"
  ci:
    strategy:
      matrix:
        runner:
          # - "macos-13"  # No code in `softboiler_github_io` right now
          # - "macos-14"  # No code in `softboiler_github_io` right now
          - "ubuntu-22.04"
          # - "windows-2022"  # No code in `softboiler_github_io` right now
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - run: "scripts/Sync-Py.ps1 -Compile -Lock -Version '3.11'"
  spaces:
    strategy:
      matrix:
        runner:
          # - "macos-13"  # No code in `softboiler_github_io` right now
          # - "macos-14"  # No code in `softboiler_github_io` right now
          - "ubuntu-22.04"
          # - "windows-2022"  # No code in `softboiler_github_io` right now
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1
        with:
          submodules: True
          path: "repo path with spaces"
      - uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c" # v5.0.0
        with:
          python-version: "3.11"
      - working-directory: "repo path with spaces"
        run: "scripts/Sync-Py.ps1 -Compile -Lock -Version '3.11'"
