# Test upper-bound project dependencies
name: "high"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 10 * * 0"
defaults:
  run:
    shell: "pwsh"
env:
  UV_CACHE_DIR: ".cache/uv-cache"
  UV_SYSTEM_PYTHON: "true"
  SYNC_PY_HIGH: "true"
jobs:
  sync:
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - uses: "actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b" # v4.3.4
        with:
          name: "lock"
          path: "lock-high.json"
  build-docs:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
        with:
          name: "lock"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; sphinx-build -EaT docs _site"
      - uses: "actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa" # v3.0.1
  ruff:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
        with:
          name: "lock"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; ruff check --no-fix --output-format github ."
  fawltydeps:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
        with:
          name: "lock"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - run: ". scripts/Initialize-Shell.ps1; fawltydeps"
  pyright:
    needs: "sync"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
        with:
          name: "lock"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1"
      - uses: "jakebailey/pyright-action@3bdde3b31d26f0f1f5de051b1fbd7a536a9a4e7f" # v4.1.7
        with:
          pylance-version: "2024.6.1"
  test:
    needs: "sync"
    strategy:
      matrix:
        runner:
          - "macos-13"
          - "ubuntu-22.04"
          - "windows-2022"
        python:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
        with:
          submodules: True
      - uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
        with:
          name: "lock"
      - uses: "actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f" # v5.1.1
        with:
          python-version: "${{ matrix.python }}"
      - run: "scripts/Sync-Py.ps1 -Version '${{ matrix.python }}'"
      - run: ". scripts/Initialize-Shell.ps1; pytest"
  lock:
    needs:
      - "ruff"
      - "fawltydeps"
      - "pyright"
      - "test"
    permissions:
      contents: "write"
    strategy:
      matrix:
        runner: ["ubuntu-22.04"]
        python: ["3.10"]
    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7
      - uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" # v4.1.8
        with:
          name: "lock"
      - uses: "stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842" # v5.0.1
        with:
          commit_message: "Sync and lock highest dependencies"
